# This historical migration records the database change identified as 0001_initial.
# It allows new and existing installations to reach the same stored structure or seed data in a
# repeatable order.
# Generated by Django 5.2.15 on 2026-07-15 18:16

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


# This class groups the information and behaviour needed for migration.
# Keeping the related rules together makes the surrounding workflow easier to reuse and test.
class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('waiting_staff', 'Waiting for Popadoo'), ('waiting_customer', 'Waiting for customer')], default='waiting_staff', max_length=24)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_message_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='customer_chat', to=settings.AUTH_USER_MODEL)),
                ('last_message_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-last_message_at', '-created_at'),
                'permissions': [('respond_to_customer_chat', 'Can view and reply to customer chats')],
            },
        ),
        migrations.CreateModel(
            name='ChatReadState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_read_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_chat_read_states', to=settings.AUTH_USER_MODEL)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_states', to='communications.customerchat')),
            ],
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_name', models.CharField(max_length=150)),
                ('sender_role', models.CharField(choices=[('customer', 'Customer'), ('administrator', 'Administrator'), ('owner', 'Owner'), ('worker', 'Worker')], max_length=24)),
                ('body', models.TextField(max_length=5000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_customer_chat_messages', to=settings.AUTH_USER_MODEL)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='communications.customerchat')),
            ],
            options={
                'ordering': ('created_at', 'pk'),
            },
        ),
        migrations.AddIndex(
            model_name='customerchat',
            index=models.Index(fields=['status', 'last_message_at'], name='communicati_status_4556e3_idx'),
        ),
        migrations.AddIndex(
            model_name='customerchat',
            index=models.Index(fields=['last_message_at'], name='communicati_last_me_d9ea72_idx'),
        ),
        migrations.AddIndex(
            model_name='customerchat',
            index=models.Index(fields=['public_id'], name='communicati_public__baf40c_idx'),
        ),
        migrations.AddIndex(
            model_name='chatreadstate',
            index=models.Index(fields=['user', 'last_read_at'], name='communicati_user_id_bf7af6_idx'),
        ),
        migrations.AddConstraint(
            model_name='chatreadstate',
            constraint=models.UniqueConstraint(fields=('chat', 'user'), name='communications_unique_chat_reader'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['chat', 'created_at'], name='communicati_chat_id_67a080_idx'),
        ),
    ]
