# Generated by Django 5.2.15 on 2026-07-10 15:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party_builder', '0008_require_catalogue_categories'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='partybuild',
            index=models.Index(fields=['event_date', 'status'], name='party_build_event_d_56ccc4_idx'),
        ),
        migrations.AddIndex(
            model_name='partybuild',
            index=models.Index(fields=['assignment_state', 'event_date'], name='party_build_assignm_f7285d_idx'),
        ),
        migrations.AddIndex(
            model_name='partybuild',
            index=models.Index(fields=['contact_email'], name='party_build_contact_59e0c5_idx'),
        ),
    ]
